#!/bin/sh

COLORBKG='7434362' 
# this value can be changed, to convert an hexa color number use this command : python -c "print 0xHexaColorNumber"

LOGOF='/Library/Application Support/BootLogo'
PLISTF='/Library/Preferences/SystemConfiguration/com.apple.Boot.plist'
install_dir=`dirname $0`


 [ -d "$LOGOF" ] || sudo mkdir "$LOGOF"
sudo cp $install_dir/logo.png $LOGOF/

sudo /usr/libexec/PlistBuddy -c 'add :"Boot Logo" string "\\Library\\Application\ Support\\BootLogo\\logo.png"' "$PLISTF"
sudo /usr/libexec/PlistBuddy -c 'add :"Background Color" integer '"$COLORBKG" "$PLISTF" # comment this line if you want to keep the default grey background

exit 0
